# Default values for andrey-node.
# This is a YAML-formatted file.

replicaCount: 2

image:
  repository: node
  pullPolicy: IfNotPresent
  tag: "14-alpine"


securityContext: {}
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

service:
  type: LoadBalancer
  port: 3000

ingress:
  enabled: true
  className: "rf-nginx"
  annotations: {}
     kubernetes.io/ingress.class: nginx
  hosts:
    - host: http-node-app.com
      paths:
        - path: /
          pathType: ImplementationSpecific

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

volumes: []
 - name: ephemeral-storage
    emptyDir: {}

volumeMounts: []
 - name: ephemeral-storage
    mountPath: "/data"
    readOnly: true